// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: token_validation.proto

package tokenvalidation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the token to validate
type TokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRequest) Reset() {
	*x = TokenRequest{}
	mi := &file_token_validation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRequest) ProtoMessage() {}

func (x *TokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_token_validation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRequest.ProtoReflect.Descriptor instead.
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return file_token_validation_proto_rawDescGZIP(), []int{0}
}

func (x *TokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// The response message
type TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // Message indicating success or failure
	Data          *UserData              `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`       // The user data if token is valid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_token_validation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_validation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_token_validation_proto_rawDescGZIP(), []int{1}
}

func (x *TokenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TokenResponse) GetData() *UserData {
	if x != nil {
		return x.Data
	}
	return nil
}

// The user data returned if the token is valid
type UserData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserData) Reset() {
	*x = UserData{}
	mi := &file_token_validation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserData) ProtoMessage() {}

func (x *UserData) ProtoReflect() protoreflect.Message {
	mi := &file_token_validation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserData.ProtoReflect.Descriptor instead.
func (*UserData) Descriptor() ([]byte, []int) {
	return file_token_validation_proto_rawDescGZIP(), []int{2}
}

func (x *UserData) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserData) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UserData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type DataUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataUser) Reset() {
	*x = DataUser{}
	mi := &file_token_validation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataUser) ProtoMessage() {}

func (x *DataUser) ProtoReflect() protoreflect.Message {
	mi := &file_token_validation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataUser.ProtoReflect.Descriptor instead.
func (*DataUser) Descriptor() ([]byte, []int) {
	return file_token_validation_proto_rawDescGZIP(), []int{3}
}

func (x *DataUser) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Data          *UserAJA               `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_token_validation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_token_validation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_token_validation_proto_rawDescGZIP(), []int{4}
}

func (x *UserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UserResponse) GetData() *UserAJA {
	if x != nil {
		return x.Data
	}
	return nil
}

type UserAJA struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAJA) Reset() {
	*x = UserAJA{}
	mi := &file_token_validation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAJA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAJA) ProtoMessage() {}

func (x *UserAJA) ProtoReflect() protoreflect.Message {
	mi := &file_token_validation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAJA.ProtoReflect.Descriptor instead.
func (*UserAJA) Descriptor() ([]byte, []int) {
	return file_token_validation_proto_rawDescGZIP(), []int{5}
}

func (x *UserAJA) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserAJA) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

var File_token_validation_proto protoreflect.FileDescriptor

const file_token_validation_proto_rawDesc = "" +
	"\n" +
	"\x16token_validation.proto\x12\x0ftokenvalidation\"$\n" +
	"\fTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"X\n" +
	"\rTokenResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12-\n" +
	"\x04data\x18\x02 \x01(\v2\x19.tokenvalidation.UserDataR\x04data\"r\n" +
	"\bUserData\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\" \n" +
	"\bDataUser\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"V\n" +
	"\fUserResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12,\n" +
	"\x04data\x18\x02 \x01(\v2\x18.tokenvalidation.UserAJAR\x04data\"B\n" +
	"\aUserAJA\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName2\xaf\x01\n" +
	"\x0fTokenValidation\x12N\n" +
	"\rValidateToken\x12\x1d.tokenvalidation.TokenRequest\x1a\x1e.tokenvalidation.TokenResponse\x12L\n" +
	"\x10ValidateDataUser\x12\x19.tokenvalidation.DataUser\x1a\x1d.tokenvalidation.UserResponseB\x13Z\x11./tokenvalidationb\x06proto3"

var (
	file_token_validation_proto_rawDescOnce sync.Once
	file_token_validation_proto_rawDescData []byte
)

func file_token_validation_proto_rawDescGZIP() []byte {
	file_token_validation_proto_rawDescOnce.Do(func() {
		file_token_validation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_token_validation_proto_rawDesc), len(file_token_validation_proto_rawDesc)))
	})
	return file_token_validation_proto_rawDescData
}

var file_token_validation_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_token_validation_proto_goTypes = []any{
	(*TokenRequest)(nil),  // 0: tokenvalidation.TokenRequest
	(*TokenResponse)(nil), // 1: tokenvalidation.TokenResponse
	(*UserData)(nil),      // 2: tokenvalidation.UserData
	(*DataUser)(nil),      // 3: tokenvalidation.DataUser
	(*UserResponse)(nil),  // 4: tokenvalidation.UserResponse
	(*UserAJA)(nil),       // 5: tokenvalidation.UserAJA
}
var file_token_validation_proto_depIdxs = []int32{
	2, // 0: tokenvalidation.TokenResponse.data:type_name -> tokenvalidation.UserData
	5, // 1: tokenvalidation.UserResponse.data:type_name -> tokenvalidation.UserAJA
	0, // 2: tokenvalidation.TokenValidation.ValidateToken:input_type -> tokenvalidation.TokenRequest
	3, // 3: tokenvalidation.TokenValidation.ValidateDataUser:input_type -> tokenvalidation.DataUser
	1, // 4: tokenvalidation.TokenValidation.ValidateToken:output_type -> tokenvalidation.TokenResponse
	4, // 5: tokenvalidation.TokenValidation.ValidateDataUser:output_type -> tokenvalidation.UserResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_token_validation_proto_init() }
func file_token_validation_proto_init() {
	if File_token_validation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_token_validation_proto_rawDesc), len(file_token_validation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_token_validation_proto_goTypes,
		DependencyIndexes: file_token_validation_proto_depIdxs,
		MessageInfos:      file_token_validation_proto_msgTypes,
	}.Build()
	File_token_validation_proto = out.File
	file_token_validation_proto_goTypes = nil
	file_token_validation_proto_depIdxs = nil
}
